name: Github Actions Demo 2
run-name: ${{ github.actor }} is learning GitHub Actions
'on':
  workflow_dispatch:
  workflow_call:
      secrets:
        peter_silly_secret:
          description: Peter Testing Secret
          required: true
          
jobs:
  print-secret:
    runs-on: ubuntu-20.04
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.PETER_SILLY_SECRET }}
        run: |
          echo "$SUPER_SECRET"
